# Generated by Django 5.0.6 on 2025-03-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.TextField()),
                ('marca', models.TextField()),
                ('modelo', models.TextField()),
                ('serie', models.TextField()),
                ('caracteristicas', models.TextField()),
                ('estado', models.CharField(max_length=10)),
                ('n_inventario', models.TextField()),
                ('resguardante', models.CharField(max_length=255)),
                ('area', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Articulos',
                'ordering': ['-created'],
            },
        ),
    ]
